FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# Maven wrapper 복사
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# 의존성 다운로드 (캐싱)
RUN chmod +x ./mvnw
RUN ./mvnw dependency:go-offline

# 소스 코드 복사
COPY src ./src

# 개발 모드로 실행
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
